---

- name: Print Red Hat release
  command: "cat /etc/redhat-release"
  register: rhrelease

- debug: msg="{{ rhrelease.stdout }}"
- debug: msg="{{ rhrelease.stderr }}"

- name: Download the Microsoft SQL Server Red Hat repository configuration file
  get_url:
    url: "{{ src_sqlsrv_repo }}"
    dest: "{{ tgt_sqlsrv_repo }}"

- name: Download the Microsoft SQL Prod Red Hat repository configuration file
  get_url:
    url: "{{ src_prod_repo }}"
    dest: "{{ tgt_prod_repo }}"

- name: Install SQL server package
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ sql_package }}"

- name: Stop SQL server service
  service:
    name: "{{ sql_service }}"
    state: stopped

- name: Set MSSQL_SA_PASSWORD step 1
  lineinfile:
    path: /root/.bashrc
    insertafter: EOF
    state: present
    line: "export MSSQL_SA_PASSWORD={{ mssql_sa_password }}"

- name: Set MSSQL_SA_PASSWORD step 2
  lineinfile:
    path: /root/.bash_profile
    insertafter: EOF
    state: present
    line: "export MSSQL_SA_PASSWORD={{ mssql_sa_password }}"

- name: Set MSSQL_PID step 1
  lineinfile:
    path: /root/.bashrc
    insertafter: EOF
    state: present
    line: "export MSSQL_PID={{ mssql_pid }}"

- name: Set MSSQL_PID step 2
  lineinfile:
    path: /root/.bash_profile
    insertafter: EOF
    state: present
    line: "export MSSQL_PID={{ mssql_pid }}"

- name: Set SQL_INSTALL_AGENT step 1
  lineinfile:
    path: /root/.bashrc
    insertafter: EOF
    state: present
    line: "export SQL_INSTALL_AGENT={{ sql_install_agent }}"

- name: Set SQL_INSTALL_AGENT step 2
  lineinfile:
    path: /root/.bash_profile
    insertafter: EOF
    state: present
    line: "export SQL_INSTALL_AGENT={{ sql_install_agent }}"

- name: Set MSSQL_SA_PASSWORD step 3
  shell: 'MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD'

- name: Set MSSQL_PID step 3
  shell: 'MSSQL_PID=$MSSQL_PID'

- name: Set SQL_INSTALL_AGENT step 3
  shell: 'SQL_INSTALL_AGENT=$SQL_INSTALL_AGENT'

- name: Install SQL Server
  shell: "/opt/mssql/bin/mssql-conf -n setup accept-eula "
  register: installsql

- debug: msg="{{ installsql.stdout }}"
- debug: msg="{{ installsql.stderr }}"

- name: Configure Firewall connections to allow remote access
  firewalld:
    state: enabled
    zone: public
    immediate: true
    port: "{{ item }}"
    permanent: true
  with_items: "{{ sql_ports }}"
