---

- name: Print Red Hat release
  command: "cat /etc/redhat-release"
  register: rhrelease

- debug: msg="{{ rhrelease.stdout }}"
- debug: msg="{{ rhrelease.stderr }}"

- name: Configure Microsoft SQL Server Red Hat repository
  yum_repository:
    name: "{{ mssql_repo }}"
    description: "{{ mssql_repo }}"
    file: external_repos
    baseurl: "{{ mssql_repo_src }}"
    gpgcheck: yes
    gpgkey: "{{ gpgkey }}"
    enabled: yes

- name: Configure Microsoft SQL Tool Red Hat repository
  yum_repository:
    name: "{{ mssql_tool_repo }}"
    description: "{{ mssql_tool_repo }}"
    file: external_repos
    baseurl: "{{ mssql_repo_tool_src }}"
    gpgcheck: yes
    gpgkey: "{{ gpgkey }}"
    enabled: yes

- name: Install SQL server package
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages: "{{ sql_package }}"

- name: Stop SQL server service
  service:
    name: "{{ sql_service }}"
    state: stopped


- name: Install SQL Server
  shell: "/opt/mssql/bin/mssql-conf -n setup accept-eula "
  environment:
    MSSQL_SA_PASSWORD: "{{ mssql_sa_password }}"
    MSSQL_PID: "{{ mssql_pid }}"
    SQL_INSTALL_AGENT: "{{ sql_install_agent }}"
  register: installsql

- debug: msg="{{ installsql.stdout }}"
- debug: msg="{{ installsql.stderr }}"

- name: Configure Firewall connections to allow remote access
  firewalld:
    state: enabled
    zone: public
    immediate: true
    port: "{{ item }}"
    permanent: true
  with_items: "{{ sql_ports }}"
